[package]
name = "neuralnet"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
calamine = "0.18"
tempfile = "3.3"
num-traits = "0.2.19"
